version: "3.7"
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./example/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  traefik:
    build: .
    image: homecentr/traefik:local
    ports:
      - "80:80"
    volumes:
      - ./example/traefik/traefik.yml:/config/traefik.yml:ro
      - ./example/traefik/nginx.yml:/nginx.yml:ro

networks:
  default:
    driver: bridge  